def disp(*a): #Here *a is caled variable length parameter whhose type is tuple...
    print(a,type(a),len(a))
    print("------------------")
    print("Number of values=",len(a))
    for val in a:
        print(val,end=",")
    print()
    print("------------------")
#Main program..
disp(10,20,30,40,50) #Function call 1 with 5 arguments...
disp(10,20,30,40) #Function call 2 with 4 arguments...
disp(10,20,30) #Function call 3 with 3 arguments...
disp(10,20) #Function call 2 with 2 arguments...
disp(10) #Function call 1 with 1 arguments...
disp() #Function call 6 with 0 arguments...
disp("TR",2+3j,True,101,102.23,"MR") #Function call 7 with 6 arguments